FROM php:8.2-apache

EXPOSE 80

RUN apt-get update && apt-get install -y \
    libfreetype-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libsqlite3-dev\
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd


RUN docker-php-ext-install \
    pdo\ 
    pdo_mysql\
    pdo_sqlite