services:
  phpapache:
    build:
      context: ./dockerfiles
      dockerfile: dockerfile_apachephp
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
      - ./config/php_conf/php.ini:/usr/local/etc/php/php.ini
      - ./config/apache_conf/apache2.conf:/etc/apache2/apache2.conf

  phpMyAdmin:
    image: phpmyadmin:latest
    ports:
      - 81:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
      - 33060:33060
