services:

  phpApache:
    image: php:8.2-apache
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql

  phpMyAdmin:
    image: phpmyadmin:latest
    ports:
      - 81:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes: 
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
      - 33060:33060
